db.menu.insertMany([
  {
    itemName: "Pappadum",
    itemDescription: "",
    itemPrice: 3.00,
    category: ObjectId("66fd6668ef4617bdbac46033"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Cucumber - Raita (Sweet or Spicy) Small",
    itemDescription: "",
    itemPrice: 3.75,
    category: ObjectId("66fd6668ef4617bdbac46033"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Cucumber - Raita (Sweet or Spicy) Large",
    itemDescription: "",
    itemPrice: 5.25,
    category: ObjectId("66fd6668ef4617bdbac46033"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Mango Chutney",
    itemDescription: "",
    itemPrice: 1.50,
    category: ObjectId("66fd6668ef4617bdbac46033"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Hot Sauce",
    itemDescription: "",
    itemPrice: 1.50,
    category: ObjectId("66fd6668ef4617bdbac46033"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Tamarind Chutney",
    itemDescription: "",
    itemPrice: 1.50,
    category: ObjectId("66fd6668ef4617bdbac46033"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Mixed Pickle",
    itemDescription: "",
    itemPrice: 1.50,
    category: ObjectId("66fd6668ef4617bdbac46033"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Indian Salad",
    itemDescription: "",
    itemPrice: 6.25,
    category: ObjectId("66fd6668ef4617bdbac46033"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Indian Raita Small",
    itemDescription: "",
    itemPrice: 4.50,
    category: ObjectId("66fd6668ef4617bdbac46033"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Indian Raita Large",
    itemDescription: "",
    itemPrice: 6.00,
    category: ObjectId("66fd6668ef4617bdbac46033"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Banana Coconut",
    itemDescription: "",
    itemPrice: 3.75,
    category: ObjectId("66fd6668ef4617bdbac46033"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  }
]);
