db.menu.insertMany([
  {
    itemName: "Butter Chicken",
    itemDescription: "Choice of meat cooked in rich and creamy sauce, tomatoes, fenugreek leaves, sugar.",
    itemPrice: 2.00,
    category: ObjectId("66fd6668ef4617bdbac46038"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Korma",
    itemDescription: "Choice of meat cooked in rich creamy cashew nut, onion gravy, green cardamom, cream, and sugar.",
    itemPrice: 2.00,
    category: ObjectId("66fd6668ef4617bdbac46038"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Jalfreji",
    itemDescription: "Choice of meat cooked in onion and capsicum, tomatoes, ginger and spices, semi-dry tangy curry.",
    itemPrice: 2.00,
    category: ObjectId("66fd6668ef4617bdbac46038"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Tikka Masala",
    itemDescription: "Choice of meat cooked in lightly spiced thick creamy sauce with capsicum, onion, fenugreek, and fresh lemon juice.",
    itemPrice: 2.00,
    category: ObjectId("66fd6668ef4617bdbac46038"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Saagwala",
    itemDescription: "Choice of meat cooked with baby spinach, garlic, Julian ginger, green chilies, fenugreek. Gift from Punjab.",
    itemPrice: 2.00,
    category: ObjectId("66fd6668ef4617bdbac46038"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Rogan Josh",
    itemDescription: "Choice of meat cooked in traditional Kashmiri curry with onion and tomato based sauce, spices, and fresh herbs.",
    itemPrice: 2.00,
    category: ObjectId("66fd6668ef4617bdbac46038"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Mango Curry",
    itemDescription: "Choice of meat cooked in rich mango sweet sauce and sultana. Classic mango chicken curry is an Aussie family favorite.",
    itemPrice: 2.00,
    category: ObjectId("66fd6668ef4617bdbac46038"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Vindaloo",
    itemDescription: "Choice of meat cooked with traditional tangy and spicy curry, garlic, jaggery, vinegar, Kashmiri chili, black pepper.",
    itemPrice: 2.00,
    category: ObjectId("66fd6668ef4617bdbac46038"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Pathia",
    itemDescription: "Choice of meat cooked with special curry originally from Persia, famous in the UK. Sweet and tangy flavored with roasted capsicum and onion.",
    itemPrice: 2.00,
    category: ObjectId("66fd6668ef4617bdbac46038"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Madras",
    itemDescription: "Choice of meat or veggies cooked with south Indian special recipe, coconut, roasted mustard seeds, coconut milk, fresh curry leaves, coriander ginger.",
    itemPrice: 2.00,
    category: ObjectId("66fd6668ef4617bdbac46038"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Kadai",
    itemDescription: "Choice of meat or veggies cooked with oven roasted pepper, diced red onion, ginger, mint, fresh coriander, and spices.",
    itemPrice: 2.00,
    category: ObjectId("66fd6668ef4617bdbac46038"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Pasanda",
    itemDescription: "Choice of meat cooked in mild spices and creamy sauce.",
    itemPrice: 2.00,
    category: ObjectId("66fd6668ef4617bdbac46038"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Mushroom Curry",
    itemDescription: "Choice of meat cooked with fresh mushrooms in mild creamy sauce.",
    itemPrice: 2.00,
    category: ObjectId("66fd6668ef4617bdbac46038"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Mughlai",
    itemDescription: "Choice of meat cooked with diced fruits, sultanas, and fresh cream.",
    itemPrice: 2.00,
    category: ObjectId("66fd6668ef4617bdbac46038"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Bhuna",
    itemDescription: "Choice of meat cooked with fresh garlic, capsicum, sliced onion, and traditional spices.",
    itemPrice: 2.00,
    category: ObjectId("66fd6668ef4617bdbac46038"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Peri Peri",
    itemDescription: "Choice of meat cooked with medium peri peri gravy and thickened cream.",
    itemPrice: 2.00,
    category: ObjectId("66fd6668ef4617bdbac46038"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Do Pyaza",
    itemDescription: "Pieces of meat cooked with yogurt, diced onion, mushroom, and creamy sauce.",
    itemPrice: 2.00,
    category: ObjectId("66fd6668ef4617bdbac46038"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Sour Lime",
    itemDescription: "Choice of meat cooked with lime juice, yogurt, and creamy sauce.",
    itemPrice: 2.00,
    category: ObjectId("66fd6668ef4617bdbac46038"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Punjabi",
    itemDescription: "Choice of meat cooked in home style Punjabi gravy with ginger, tomato, onion, coriander, and special blend of Punjabi spices.",
    itemPrice: 2.00,
    category: ObjectId("66fd6668ef4617bdbac46038"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Meat Kofta Curry",
    itemDescription: "Meatballs cooked with creamy sauce, grounded cashews, and mild spices.",
    itemPrice: 2.00,
    category: ObjectId("66fd6668ef4617bdbac46038"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Egg Curry",
    itemDescription: "Boiled eggs cooked in chef style gravy and ground spices.",
    itemPrice: 2.00,
    category: ObjectId("66fd6668ef4617bdbac46038"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Egg Bhurji (Dry Curry)",
    itemDescription: "Scrambled eggs dish which includes onion, tomatoes, ginger, garlic and coriander , spices.",
    itemPrice: 2.00,
    category: ObjectId("66fd6668ef4617bdbac46038"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]);
 
