db.menu.insertMany([
  {
    itemName: "Rasgulla (3 pc)",
    itemDescription: "",
    itemPrice: 3.95,
    category: ObjectId("66fd6668ef4617bdbac46034"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Gulab jamun (3 pc)",
    itemDescription: "",
    itemPrice: 3.75,
    category: ObjectId("66fd6668ef4617bdbac46034"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Ice-Cream",
    itemDescription: "",
    itemPrice: 5.50,
    category: ObjectId("66fd6668ef4617bdbac46034"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Banana Split",
    itemDescription: "",
    itemPrice: 7.90,
    category: ObjectId("66fd6668ef4617bdbac46034"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  }
]);
