db.menu.insertMany([
  {
    itemName: "Soft Drinks",
    itemDescription: "",
    itemPrice: 3.00,
    category: ObjectId("66fd6668ef4617bdbac46035"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Lemon Lime Bitters",
    itemDescription: "",
    itemPrice: 5.50,
    category: ObjectId("66fd6668ef4617bdbac46035"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Ginger Beer",
    itemDescription: "",
    itemPrice: 4.50,
    category: ObjectId("66fd6668ef4617bdbac46035"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Mango Lassi",
    itemDescription: "",
    itemPrice: 3.95,
    category: ObjectId("66fd6668ef4617bdbac46035"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Passion Fruit Lassi",
    itemDescription: "",
    itemPrice: 3.95,
    category: ObjectId("66fd6668ef4617bdbac46035"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Rose / Sweet Lassi",
    itemDescription: "",
    itemPrice: 3.95,
    category: ObjectId("66fd6668ef4617bdbac46035"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Strawberry Lassi",
    itemDescription: "",
    itemPrice: 3.95,
    category: ObjectId("66fd6668ef4617bdbac46035"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Punjabi Lassi",
    itemDescription: "",
    itemPrice: 3.95,
    category: ObjectId("66fd6668ef4617bdbac46035"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Indian Tea",
    itemDescription: "",
    itemPrice: 4.95,
    category: ObjectId("66fd6668ef4617bdbac46035"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  }
]);
