db.menu.insertMany([
  {
    itemName: "Spring rolls (4 piece)",
    itemDescription: "",
    itemPrice: 9.90,
    category: ObjectId("66fd6668ef4617bdbac46036"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Onion Bhaji (4 piece)",
    itemDescription: "Slice onion and chickpeas flour, mixed spices deep fried in vegetable oil",
    itemPrice: 10.00,
    category: ObjectId("66fd6668ef4617bdbac46036"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Vegetarian Samosa (2 piece)",
    itemDescription: "Mix of spiced potatoes, onion, fenugreek, peas and exotic spices stuffed in hand made pastry.",
    itemPrice: 10.90,
    category: ObjectId("66fd6668ef4617bdbac46036"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Vegetable Pakora (4 piece)",
    itemDescription: "Selected vegetables mixed with Indian spices. Chickpea flour and deep fried.",
    itemPrice: 9.90,
    category: ObjectId("66fd6668ef4617bdbac46036"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Paneer Pakora (4 piece)",
    itemDescription: "Cottage cheese cubes delicately spiced dipped in batter and deep fried.",
    itemPrice: 12.90,
    category: ObjectId("66fd6668ef4617bdbac46036"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Mushroom Pakora (4 piece)",
    itemDescription: "Fresh mushrooms are delicately spiced, dipped in batter and deep fried.",
    itemPrice: 10.90,
    category: ObjectId("66fd6668ef4617bdbac46036"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Chicken Pakora (4 piece)",
    itemDescription: "Pieces of boneless chicken, dipped in batter and deep fried.",
    itemPrice: 13.90,
    category: ObjectId("66fd6668ef4617bdbac46036"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Prawn Pakora (4 piece)",
    itemDescription: "Marinated Prawns dipped into batter and deep fried.",
    itemPrice: 17.90,
    category: ObjectId("66fd6668ef4617bdbac46036"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Tandoori Chicken (with bones) (4 piece)",
    itemDescription: "Chicken marinated in yoghurt, garlic and selected herbs and cooked in tandoor.",
    itemPrice: 14.90,
    category: ObjectId("66fd6668ef4617bdbac46036"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Lamb Sheesh Kebab (4 piece)",
    itemDescription: "Finger rolls of lamb with exotic spices skewered in tandoor.",
    itemPrice: 14.90,
    category: ObjectId("66fd6668ef4617bdbac46036"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Fish Pakora (4 piece)",
    itemDescription: "Spiced marinated fried fish.",
    itemPrice: 14.90,
    category: ObjectId("66fd6668ef4617bdbac46036"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Meat Samosa (2 piece)",
    itemDescription: "Mix of spices potatoes, onion, fenugreek, peas, minced meat and mild spices stuffed in hand made pastry.",
    itemPrice: 11.90,
    category: ObjectId("66fd6668ef4617bdbac46036"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  }
]);
