db.menu.insertMany([
  {
    itemName: "Chicken",
    itemDescription: "",
    itemPrice: 19.99,
    category: ObjectId("66fd842aef4617bdbac460c8"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Beef",
    itemDescription: "",
    itemPrice: 20.99,
    category: ObjectId("66fd842aef4617bdbac460c8"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Lamb",
    itemDescription: "",
    itemPrice: 20.99,
    category: ObjectId("66fd842aef4617bdbac460c8"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Prawn",
    itemDescription: "",
    itemPrice: 22.99,
    category: ObjectId("66fd842aef4617bdbac460c8"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Goat",
    itemDescription: "",
    itemPrice: 20.99,
    category: ObjectId("66fd842aef4617bdbac460c8"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Vegetable",
    itemDescription: "Spice level - mild, medium, hot, Indian hot",
    itemPrice: 19.99,
    category: ObjectId("66fd842aef4617bdbac460c8"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  }
]);
