db.menu.insertMany([
  {
    itemName: "Fish Chips",
    itemDescription: "",
    itemPrice: 10.90,
    category: ObjectId("66fd6668ef4617bdbac46037"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Chicken Nuggets and Chips",
    itemDescription: "",
    itemPrice: 11.90,
    category: ObjectId("66fd6668ef4617bdbac46037"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Chips",
    itemDescription: "",
    itemPrice: 6.50,
    category: ObjectId("66fd6668ef4617bdbac46037"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Kids Butter Chicken",
    itemDescription: "",
    itemPrice: 11.90,
    category: ObjectId("66fd6668ef4617bdbac46037"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Kids Mango Chicken",
    itemDescription: "",
    itemPrice: 11.90,
    category: ObjectId("66fd6668ef4617bdbac46037"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  }
]);
