db.menu.insertMany([
  {
    itemName: "Plain Naan",
    itemDescription: "Leavened original bread with a touch of butter.",
    itemPrice: 4.25,
    category: ObjectId("66fd6668ef4617bdbac4603f"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Garlic Naan",
    itemDescription: "Naan with touch of garlic, butter, and garnished with coriander.",
    itemPrice: 5.25,
    category: ObjectId("66fd6668ef4617bdbac4603f"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Cheese Naan",
    itemDescription: "Naan stuffed with cheese.",
    itemPrice: 5.99,
    category: ObjectId("66fd6668ef4617bdbac4603f"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Cheese & Garlic Naan",
    itemDescription: "Naan stuffed with cheese and garnished with coriander.",
    itemPrice: 6.50,
    category: ObjectId("66fd6668ef4617bdbac4603f"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Cheese and Spinach Naan",
    itemDescription: "Naan stuffed with spinach and cheese.",
    itemPrice: 6.99,
    category: ObjectId("66fd6668ef4617bdbac4603f"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Peswari Naan (Sweet)",
    itemDescription: "Naan stuffed with royal dry fruits and glazed with butter.",
    itemPrice: 6.99,
    category: ObjectId("66fd6668ef4617bdbac4603f"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Keema Kulcha",
    itemDescription: "Naan stuffed with lamb mince and mild spices.",
    itemPrice: 6.99,
    category: ObjectId("66fd6668ef4617bdbac4603f"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Keema and Cheese Naan",
    itemDescription: "Naan stuffed with lamb mince, cheese, coriander, and mild spices.",
    itemPrice: 6.95,
    category: ObjectId("66fd6668ef4617bdbac4603f"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Chicken Cheese Naan",
    itemDescription: "Naan stuffed with chicken, cheese, coriander, and mild spices.",
    itemPrice: 6.95,
    category: ObjectId("66fd6668ef4617bdbac4603f"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Chocolate Naan",
    itemDescription: "Naan bread stuffed with chocolate.",
    itemPrice: 6.95,
    category: ObjectId("66fd6668ef4617bdbac4603f"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Paneer And Onion Naan",
    itemDescription: "Naan stuffed with cottage cheese and onion with medium spices.",
    itemPrice: 7.25,
    category: ObjectId("66fd6668ef4617bdbac4603f"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Capsicum & Onion Naan",
    itemDescription: "Naan stuffed with cottage cheese and onion with medium spices.",
    itemPrice: 6.95,
    category: ObjectId("66fd6668ef4617bdbac4603f"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Chilli & Cheese Naan",
    itemDescription: "Naan stuffed with cottage cheese and onion with medium spices.",
    itemPrice: 5.95,
    category: ObjectId("66fd6668ef4617bdbac4603f"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Aloo Kulcha",
    itemDescription: "Naan bread stuffed with mashed potatoes, onion, fresh chillies, spices, and garnished with coriander.",
    itemPrice: 6.95,
    category: ObjectId("66fd6668ef4617bdbac4603f"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Onion Kulcha",
    itemDescription: "Naan bread stuffed with mashed potatoes, onion, fresh chillies, spices, and garnished with coriander.",
    itemPrice: 5.95,
    category: ObjectId("66fd6668ef4617bdbac4603f"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Roti (Tandoori)",
    itemDescription: "Wholemeal bread with a touch of butter.",
    itemPrice: 3.99,
    category: ObjectId("66fd6668ef4617bdbac4603f"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Garlic Roti",
    itemDescription: "Wholemeal bread with a touch of garlic and butter.",
    itemPrice: 4.50,
    category: ObjectId("66fd6668ef4617bdbac4603f"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Bread Platter",
    itemDescription: "Plain naan + Garlic naan + Cheese and garlic naan.",
    itemPrice: 15.50,
    category: ObjectId("66fd6668ef4617bdbac4603f"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Panjabi Chilli Naan",
    itemDescription: "Naan stuffed with diced capsicum, onion, cottage cheese, green chilli.",
    itemPrice: 8.50,
    category: ObjectId("66fd6668ef4617bdbac4603f"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  }
]);
