db.menu.insertMany([
  {
    itemName: "Plain Rice",
    itemDescription: "",
    itemPrice: 2.90,
    category: ObjectId("66fd6668ef4617bdbac4603d"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Saffron Rice",
    itemDescription: "",
    itemPrice: 3.90,
    category: ObjectId("66fd6668ef4617bdbac4603d"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Matar Palao",
    itemDescription: "Rice with peas cooked in spices.",
    itemPrice: 6.99,
    category: ObjectId("66fd6668ef4617bdbac4603d"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Vegetable Biryani",
    itemDescription: "Aromatic basmati rice cooked with vegetables and mild spices. It comes with cucumber raita which is sweet or spicy.",
    itemPrice: 19.99,
    category: ObjectId("66fd6668ef4617bdbac4603d"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Chicken Biryani",
    itemDescription: "Aromatic basmati rice cooked with chicken, capsicum, onion and blend of spices.",
    itemPrice: 20.99,
    category: ObjectId("66fd6668ef4617bdbac4603d"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Beef Biryani",
    itemDescription: "Basmati rice cooked together with meat, capsicum, onion, herbs and spices.",
    itemPrice: 20.99,
    category: ObjectId("66fd6668ef4617bdbac4603d"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Prawn Biryani",
    itemDescription: "Basmati rice cooked together with prawns, capsicum, onion and selected spices.",
    itemPrice: 20.99,
    category: ObjectId("66fd6668ef4617bdbac4603d"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Coconut Rice",
    itemDescription: "Aromatic saffron rice cooked with coconut milk, mustard seeds and served with coconut flakes.",
    itemPrice: 6.50,
    category: ObjectId("66fd6668ef4617bdbac4603d"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Jeera Rice",
    itemDescription: "Popular north Indian dish cooked from aromatic basmati rice seasoned with cumin seeds.",
    itemPrice: 5.90,
    category: ObjectId("66fd6668ef4617bdbac4603d"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Egg-Fried Rice",
    itemDescription: "Aromatic rice cooked with scrambled egg and selected spices.",
    itemPrice: 7.90,
    category: ObjectId("66fd6668ef4617bdbac4603d"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Veggie Fried Rice",
    itemDescription: "Rice cooked with selected vegetables, spices and finished with coriander.",
    itemPrice: 7.90,
    category: ObjectId("66fd6668ef4617bdbac4603d"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Lamb Biryani",
    itemDescription: "Basmati rice cooked together with meat, capsicum, onion, herbs and spices.",
    itemPrice: 22.99,
    category: ObjectId("66fd6668ef4617bdbac4603d"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  }
]);
