db.menu.insertMany([
  {
    itemName: "Tikki Chole Chat",
    itemDescription: "Crispy potato patties topped with sweet, sour and spicy chutney, yogurt and coriander.",
    itemPrice: 9.99,
    category: ObjectId("66fd6668ef4617bdbac4603b"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Pav Bhaji (2 pc)",
    itemDescription: "",
    itemPrice: 11.90,
    category: ObjectId("66fd6668ef4617bdbac4603b"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Extra Pav (1 PC)",
    itemDescription: "",
    itemPrice: 2.50,
    category: ObjectId("66fd6668ef4617bdbac4603b"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Chole Bhature (2 pc)",
    itemDescription: "Chole (spicy chickpea curry) served with fried bread.",
    itemPrice: 16.90,
    category: ObjectId("66fd6668ef4617bdbac4603b"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Extra Bhatura (1 pc)",
    itemDescription: "",
    itemPrice: 3.00,
    category: ObjectId("66fd6668ef4617bdbac4603b"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Samosa Chat",
    itemDescription: "Crunchy samosa is served with spicy chick pea curry.",
    itemPrice: 10.99,
    category: ObjectId("66fd6668ef4617bdbac4603b"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Chat Papdi",
    itemDescription: "Combination of papdi, sev, sweet yogurt, green chutney and tamarind chutney.",
    itemPrice: 10.99,
    category: ObjectId("66fd6668ef4617bdbac4603b"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Dahi Bhalla",
    itemDescription: "Dahi vada fried lentil fritters soft ball soaked in creamy yoghurt with spices, sweet and mild spicy.",
    itemPrice: 11.99,
    category: ObjectId("66fd6668ef4617bdbac4603b"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Aloo Tikki",
    itemDescription: "Crispy potato patties made with potatoes, green chilli and spices. Served with chick pea curry.",
    itemPrice: 10.99,
    category: ObjectId("66fd6668ef4617bdbac4603b"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Paneer Paratha (1 pc)",
    itemDescription: "Indian flat bread stuffed with cottage cheese, spices and cooked with butter.",
    itemPrice: 9.90,
    category: ObjectId("66fd6668ef4617bdbac4603b"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Aloo Paratha (1 pc)",
    itemDescription: "Indian flat bread stuffed with potatoes, spiced up with Indian spices and cooked with butter.",
    itemPrice: 9.90,
    category: ObjectId("66fd6668ef4617bdbac4603b"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Gobhi Paratha (1 pc)",
    itemDescription: "Indian flat bread stuffed with cauliflower, spiced and cooked with butter.",
    itemPrice: 9.90,
    category: ObjectId("66fd6668ef4617bdbac4603b"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Tawa Roti (1 pc)",
    itemDescription: "",
    itemPrice: 3.25,
    category: ObjectId("66fd6668ef4617bdbac4603b"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  }
]);
