db.menu.insertMany([
  {
    itemName: "Yellow Daal Tadka",
    itemDescription: "Pan fry yellow lentils cooked in mild spices and herbs with garlic and onion flavour will surprise your taste buds.",
    itemPrice: 19.99,
    category: ObjectId("66fd6668ef4617bdbac46039"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Aloo Gobhi",
    itemDescription: "Culiflower & potatoes tampered in tomato, red onion, garlic and spices.",
    itemPrice: 19.99,
    category: ObjectId("66fd6668ef4617bdbac46039"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Butter Paneer",
    itemDescription: "Rich and creamy sauce, plum tomatoes, fenugreek leaves, palm sugar.",
    itemPrice: 19.99,
    category: ObjectId("66fd6668ef4617bdbac46039"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Bombay Aloo",
    itemDescription: "Stir fry potatoes, cooked in tangy tomato sauce, spices, and herbs.",
    itemPrice: 19.99,
    category: ObjectId("66fd6668ef4617bdbac46039"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Daal Makhni",
    itemDescription: "Mixed black lentils soaked overnight and slow cooked with tomatoes, ginger, garlic, onion and touch of cream and butter.",
    itemPrice: 19.99,
    category: ObjectId("66fd6668ef4617bdbac46039"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Kadai Paneer",
    itemDescription: "Cottage cheese, roasted capsicum, onion, fenugreek, mint, spices in semi-dry sauce.",
    itemPrice: 19.99,
    category: ObjectId("66fd6668ef4617bdbac46039"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Vegetable Jalfreji",
    itemDescription: "Desire boiled vegetables, turmeric, cumin seed, ginger, garlic and spice (dry curry).",
    itemPrice: 19.99,
    category: ObjectId("66fd6668ef4617bdbac46039"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Malai Kofta",
    itemDescription: "Homemade balls of potato cooked with cashew, cream, fennel and sultanas.",
    itemPrice: 19.99,
    category: ObjectId("66fd6668ef4617bdbac46039"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Vegetable Korma",
    itemDescription: "Mixed vegetables cooked in creamy sauce with palm sugar, cashew and spices.",
    itemPrice: 19.99,
    category: ObjectId("66fd6668ef4617bdbac46039"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Palak Paneer",
    itemDescription: "Cottage cheese, baby spinach, fenugreek leaves, green chillies if hot, ginger, tomato.",
    itemPrice: 19.99,
    category: ObjectId("66fd6668ef4617bdbac46039"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Punjabi Daal",
    itemDescription: "Mixed black lentils soaked overnight and slow cooked with tomatoes, ginger, garlic, onion.",
    itemPrice: 19.99,
    category: ObjectId("66fd6668ef4617bdbac46039"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Methi Malai Paneer",
    itemDescription: "Pieces of meat cooked with fenugreek, creamy sauce and mild authentic Indian spices.",
    itemPrice: 19.99,
    category: ObjectId("66fd6668ef4617bdbac46039"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Matar Paneer",
    itemDescription: "Cubes of cottage cheese and garden peas cooked with onion sauce and exotic spices.",
    itemPrice: 19.99,
    category: ObjectId("66fd6668ef4617bdbac46039"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Butter Paneer",
    itemDescription: "Cubes of cottage cheese cooked in rich creamy sauce made with tomatoes, butter and mild spices.",
    itemPrice: 19.99,
    category: ObjectId("66fd6668ef4617bdbac46039"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Zenobia",
    itemDescription: "Balls of cottage cheese, potatoes cooked in rich sauce made from tomatoes, cream, butter and mild spices.",
    itemPrice: 19.99,
    category: ObjectId("66fd6668ef4617bdbac46039"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Eggplant & Aloo Curry",
    itemDescription: "Diced eggplant and potatoes cooked with selective Punjabi spices.",
    itemPrice: 19.99,
    category: ObjectId("66fd6668ef4617bdbac46039"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Punjabi Veggie Curry",
    itemDescription: "Mixed vegetables - mushroom, potatoes, garden peas cooked with onion.",
    itemPrice: 19.99,
    category: ObjectId("66fd6668ef4617bdbac46039"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Matar Mushroom",
    itemDescription: "Mushroom and garden peas cooked in medium spices.",
    itemPrice: 19.99,
    category: ObjectId("66fd6668ef4617bdbac46039"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  }
]);
