db.menu.insertMany([
  {
    itemName: "Vegan Butter Chicken (GF) (DF)",
    itemDescription: "(Soy chunks or potatoes) plum tomato, coconut cream, fenugreek.",
    itemPrice: 19.99,
    category: ObjectId("66fd6668ef4617bdbac4603e"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Vegan Veg Korma (GF) (DF)",
    itemDescription: "Mixed vegetables cooked in coconut creamy sauce with cashew and spices.",
    itemPrice: 19.99,
    category: ObjectId("66fd6668ef4617bdbac4603e"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Subzi",
    itemDescription: "Your choice of meat cooked with ginger, coriander & fresh vegetables with medium spices.",
    itemPrice: 19.99,
    category: ObjectId("66fd6668ef4617bdbac4603e"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  }
]);
