db.menu.insertMany([
  {
    itemName: "Vegan Plain Naan",
    itemDescription: "",
    itemPrice: 3.25,
    category: ObjectId("66fd6668ef4617bdbac4603c"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Vegan Garlic Naan",
    itemDescription: "",
    itemPrice: 4.25,
    category: ObjectId("66fd6668ef4617bdbac4603c"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Vegan Garlic Roti",
    itemDescription: "",
    itemPrice: 4.25,
    category: ObjectId("66fd6668ef4617bdbac4603c"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Vegan Roti",
    itemDescription: "",
    itemPrice: 4.25,
    category: ObjectId("66fd6668ef4617bdbac4603c"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Vegan Mint Paratha",
    itemDescription: "",
    itemPrice: 4.25,
    category: ObjectId("66fd6668ef4617bdbac4603c"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    itemName: "Vegan Onion Bread",
    itemDescription: "",
    itemPrice: 5.25,
    category: ObjectId("66fd6668ef4617bdbac4603c"),
    recordDeleted: false,
    createdBy: null,
    updatedBy: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  }
]);
